# Generated by Django 5.0.3 on 2024-06-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='iscompleted',
            field=models.BooleanField(default=False),
        ),
    ]
